version: 2

sources:
  - name: silverscreen #name of the source you will reference in the models
    database: silverscreen #name of database
    schema: public
    tables:
      - name: movie_catalogue
        description: "Detailed information on the movie"
      - name: ticketsales_nj_001
        description: "Raw NJ_001 transaction data with tickets and details on discount and film"
        columns:
          - name: movie_id
            tests:
              - not_null
          - name: TIMESTAMP
            tests:
              - not_null
          - name: ticket_amount
            tests:
              - not_null
          - name: transaction_total
            tests:
              - not_null
          - name: IS_3D
            tests:
              - not_null
              - accepted_values:
                  values: [true, false]
          - name: IS_DISCOUNTED
            tests:
              - not_null
              - accepted_values:
                  values: [true, false]
          - name: TRANSACTION_ID
            tests:
              - not_null
              - unique
          - name: PRICE
            tests:
              - not_null
      - name: ticketsales_nj_002
        description: "Raw NJ_002 transaction data with ticketssales, in amount, price and totals"
        columns:
          - name: movie_id
            tests:
              - not_null
          - name: date
            tests:
              - not_null
      - name: ticketsales_nj_003
        description: "Raw NJ_003 transaction data with ticketssales and other productsales, in amount, price and totals"
        columns:
          - name: DETAILS
      - name: invoices
models:
  - name: stg_ticketsales_nj_001_cleaned
    description: this creates a cleaned table of monthly aggregated ticketsales in location 001 used for the main mart
    columns:
      - name: MONTH
        tests:
          - not_null
      - name: TOTAL_REVENUE
        tests:
          - not_null
      - name: TOTAL_TICKETS_SOLD
        tests:
          - not_null
      - name: location_id
        description: "The identifier for the location, set to 'NJ_001'."
        tests:
          - not_null
          - accepted_values:
              values: ['NJ_001']
        
  - name: stg_ticketsales_nj_003_cleaned
    description: this creates a cleaned table of monthly aggregated ticketsales in location 003 used for the main mart
    columns:
      - name: MONTH
        tests:
          - not_null
      - name: TOTAL_REVENUE
        tests:
          - not_null
      - name: TOTAL_TICKETS_SOLD
        tests:
          - not_null
      - name: location_id
        description: "The identifier for the location, set to 'NJ_003'."
        tests:
          - not_null
          - accepted_values:
              values: ['NJ_003']
          
  - name: stg_ticketsales_nj_002_cleaned
    description: this creates a cleaned table of monthly aggregated ticketsales in location 002 used for the main mart
    columns:
      - name: MONTH
        tests:
          - not_null
      - name: TOTAL_REVENUE
        tests:
          - not_null
      - name: TOTAL_TICKETS_SOLD
        tests:
          - not_null
      - name: location_id
        description: "The static identifier for the location, set to 'NJ_002'."
        tests:
          - not_null
          - accepted_values:
              values: ['NJ_002']    
  - name: int_sales_by_month
    description: "unions sales from all locations and aggregates it by month"
    columns:
      - name: month
        description: "The first day of the month for which sales are aggregated."
        tests:
          - not_null
      - name: location_id
        description: "The identifier for the movie theater location "
        tests:
          - not_null
          - accepted_values:
              values: ['NJ_001', 'NJ_002', 'NJ_003']
      - name: movie_id
        tests:
          - not_null
      - name: total_tickets_sold
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue from ticket sales by movie, location, and month."
        tests:
          - not_null
  - name: stg_movie_catalogue_cleaned
    description: "Staging model for the movie catalogue."
    columns:
      - name: movie_id
        description: "The unique identifier for each movie. This is primary key."
        tests:
          - unique
          - not_null
      - name: movie_title
        tests:
          - not_null
      - name: release_date
      - name: genre
        description: "The movie genre. Missing values  filled with 'Unknown'."
        tests:
          - not_null
      - name: studio

  - name: marts_movie_final
    description: "Final table that combines monthly sales, costs, and movie details"
    columns:
      - name: month
        tests:
          - not_null
      - name: location_id
        description: "The identifier of the movie theater location."
        tests:
          - not_null
      - name: movie_id
        description: "The unique identifier for the movie."
        tests:
          - not_null
      - name: movie_title
      - name: genre
      - name: studio
      - name: total_tickets_sold
        description: "Total number of tickets sold."
        tests:
          - not_null
      - name: total_revenue
        tests:
          - not_null
      - name: rental_cost
        description: "Total cost of renting the movie for the month"
        tests:
          - not_null

       
      