version: 2

sources:
  - name: silverscreen #name of the source you will reference in the models
    database: silverscreen #name of database
    schema: public
    tables:
      - name: movie_catalogue
        description: "Detailed information on the movie"
      - name: ticketsales_nj_001
        description: "Raw NJ_001 transaction data with tickets and details on discount and film"
        columns:
          - name: movie_id
            tests:
              - not_null
          - name: TIMESTAMP
            tests:
              - not_null
          - name: ticket_amount
            tests:
              - not_null
          - name: transaction_total
            tests:
              - not_null
          - name: IS_3D
            tests:
              - not_null
              - accepted_values:
                  values: [true, false]
          - name: IS_DISCOUNTED
            tests:
              - not_null
              - accepted_values:
                  values: [true, false]
          - name: TRANSACTION_ID
            tests:
              - not_null
              - unique
          - name: PRICE
            tests:
              - not_null
      - name: ticketsales_nj_002
        description: "Raw NJ_002 transaction data with ticketssales, in amount, price and totals"
        columns:
          - name: movie_id
            tests:
              - not_null
          - name: date
            tests:
              - not_null
      - name: ticketsales_nj_003
        description: "Raw NJ_003 transaction data with ticketssales, in amount, price and totals"
        columns:
          - name: DETAILS
      - name: invoices
models:
  - name: stg_ticketsales_nj_001_cleaned
    description: this creates a cleaned table of monthly aggregated ticketsales in location 001 used for the main mart
    columns:
      - name: MONTH
        tests:
          - not_null
      - name: TOTAL_REVENUE
        tests:
          - not_null
      - name: TOTAL_TICKETS_SOLD
        tests:
          - not_null
        
  - name: stg_ticketsales_nj_003_cleaned
    description: this creates a cleaned table of monthly aggregated ticketsales in location 003 used for the main mart
    columns:
      - name: MONTH
        tests:
          - not_null
      - name: TOTAL_REVENUE
        tests:
          - not_null
      - name: TOTAL_TICKETS_SOLD
        tests:
          - not_null
          
  - name: stg_ticketsales_nj_002_cleaned
    description: this model filters out users who haven't completed registration
    columns:
      - name: MONTH
        tests:
          - not_null
      - name: TOTAL_REVENUE
        tests:
          - not_null
      - name: TOTAL_TICKETS_SOLD
        tests:
          - not_null
      
  - name: stg_movie_catalogue_cleaned
    description: this creates a cleaned table of monthly aggregated ticketsales in location 002 used for the main mart
    columns:
      - name: RELEASE_DATE
        tests:
          - not_null
      - name: MOVIE_ID
        tests:
          - not_null
          - unique
      - name: BUDGET
        tests:
          - not_null
  - name: int_ticketsales_nj_all
    description: this creates a cleaned table of monthly aggregated ticketsales for all locations used for the main marts
    columns:
      - name: MONTH
        tests:
          - not_null
      - name: MOVIE_ID
        tests:
          - not_null
      - name: TOTAL_REVENUE
        tests:
          - not_null
      - name: TOTAL_TICKETS_SOLD
        tests:
          - not_null
         
  - name: int_movie_costs_by_location
    description: this creates a cleaned table of monthly rental costas per movie per location used for the main mart
    columns:
      - name: MONTH
        tests:
          - not_null
      - name: INVOICE_ID
        tests:
          - not_null
      - name: LOCATION_ID
        tests:
          - not_null
      - name: MOVIE_ID
        tests:
          - not_null
      - name: RENTAL_COST
        tests:
          - not_null
       
  - name: marts_movie_cost_rev
    description: this creates a cleaned table of monthly rental costs and revenue per movie per location and sold tickets
    columns:
      - name: MONTH
        tests:
          - not_null
      - name: TICKETS_SOLD
        tests:
          - not_null
    
      - name: REVENUE
        tests:
          - not_null
      - name: RENTAL_COST
        tests:
          - not_null
       
      